SHARPBANGSCRIPTS=true
BYTECC=i686-myos-elf-gcc
BYTECCCOMPOPTS=-fno-defer-pop -Wall
MKEXE=$(BYTECC)

CCLIBS=-lm
BYTECCLIBS=$(CCLIBS)

RANLIB=i686-myos-elf-ranlib
RANLIBCMD=i686-myos-elf-ranlib

ARCMD=i686-myos-elf-ar
A=a
O=o
EXT_OBJ=.o
EXT_ASM=.s
EXT_LIB=.a

RUNTIMED=noruntimed
